### ISSUE TITLE
Did you know Companion?

### ISSUE THREAD

**Issue by fmalcher** [Wolverine80/SoundCraftUi24R#1]
Hi @Wolverine80 🙂 This seems to be the only way to contact you through GitHub. I just stumbled across this repo and I really love seeing that people develop things for StreamDeck and Soundcraft Ui Mixers 👍

Do you know the Companion project? https://bitfocus.io/companion/
It's an additional software, but integrates well into the StreamDeck. I just recently worked on a rewrite of the soundcraft-ui module for Companion which includes most functionality of the mixer.

If you decided to not use Companion, may I ask what were the reasons for this?
Thanks – and keep on coding! 🙂

**Comment by Wolverine80** [comment]
> Hi @Wolverine80 🙂 This seems to be the only way to contact you through GitHub. I just stumbled across this repo and I really love seeing that people develop things for StreamDeck and Soundcraft Ui Mixers 👍
> 
> Do you know the Companion project? https://bitfocus.io/companion/
> It's an additional software, but integrates well into the StreamDeck. I just recently worked on a rewrite of the soundcraft-ui module for Companion which includes most functionality of the mixer.
> 
> If you decided to not use Companion, may I ask what were the reasons for this?
> Thanks – and keep on coding! 🙂

Hi,

I primarily use the app for switching profiles and mute groups. Both not possible with companion at the moment. Also I need the feedback when activating a mute group to see which one is active.

**Comment by fmalcher** [comment]
With the newest version of the module, mute groups (incl. feedback) are supported! 😊 

Would you mind creating an issue in my connection lib for profile switching? I will add this to the lob and to the companion module then.
